version: "2"

services:
   db:
     image: mysql:5.7
     container_name: mysql
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_DATABASE: symfony
       MYSQL_USER: symfony
       MYSQL_PASSWORD: symfonypass
     ports:
         - "3307:3306"
     expose:
         - "3306"

   apache:
     build: apache
     container_name: apache
     ports:
       - "8080:80"
     expose:
         - "80"
     restart: always
     volumes:
         - ${SYMFONY_PATH}:/var/www/app
     # https://stackoverflow.com/questions/37100358/docker-composer-exited-with-code-0
     tty: true
     depends_on:
         - db


volumes:
    db_data:
